### ISSUE TITLE
Vue-admin backstage management system template left navigation bar can not be added to solve!

### ISSUE THREAD

**Issue by 858337881** [huanent/vue-admin#1]
I want to use your Vue background management model, but the content is a little bit less, I want to add content in the left navigation bar and head, but I can not add it, solve!

**Comment by huanent** [comment]
this repository will be Archived,please see https://github.com/huanent/vue-quickstart 
you can add left navigation bar item in https://github.com/huanent/vue-quickstart/blob/master/src/api/Menu.js
